#server.port=8085
#spring.application.name=Expense-Tracking-System

spring.datasource.url=jdbc:postgresql://db.tourzgafriszkwvahtwu.supabase.co:5432/postgres
#spring.datasource.url=jdbc:postgresql://postgres:Sudip%402560@db.tourzgafriszkwvahtwu.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Sudip@2560
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

#spring.datasource.url=postgresql://postgres:Sudip@2560@db.tourzgafriszkwvahtwu.supabase.co:5432/postgres

#spring.datasource.username=postgres
#spring.datasource.password=Sudip@2560stock_ddsq

logging.level.org.thymeleaf=DEBUG

# Email configuration (for demo - configure for your email provider)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sudipmanandhar2560@gmail.com
spring.mail.password=nbqi frdv kszx nela
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.main.allow-circular-references=true
# Server
server.address=0.0.0.0
server.port=8081
